import { RxDashboard } from "react-icons/rx";

export const sidebarItems = [
  { path: "/", name: "Dashboard", icon: <RxDashboard /> },
  // { path: "/category", name: "Category", icon: <IoNewspaperOutline /> },
  // { path: "/company", name: "Company", icon: <HiOutlineBuildingOffice2 /> },
  // { path: "/product", name: "Product", icon: <AiOutlineProduct /> },
  // { path: "/banner", name: "Banner", icon: <FaRegImage /> },
  // { path: "/order", name: "Order", icon: <BsBagCheck /> },
  // { path: "/sales-report", name: "Sale Report", icon: <TbReportSearch /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-users", name: "All Users", icon: <HiUsers /> },
  // { path: "/all-staff", name: "All Staff", icon: <PiUserCircleCheckLight /> },
];
